// Base de datos de miles de videojuegos clasificados para La Selectora de Juegos
export interface GameEntry {
  id: string;
  name: string;
  category: string;
  platform?: string;
  keywords?: string[];
  isMultiPlatformMod?: boolean; // Para Roblox y Fortnite
}

export const GAMES_CATALOG: GameEntry[] = [
  // --- PLATAFORMAS MULTIJUEGOS ---
  { id: 'roblox', name: 'Roblox', category: 'Multijuego / Sandbox', platform: 'PC / Consolas / Móvil', isMultiPlatformMod: true, keywords: ['roblox', 'roblx', 'bloxfruits', 'evade', 'doors', 'brookhaven', 'adopt me', 'blade ball', 'dress to impress', 'forsaken', 'forzaken'] },
  { id: 'fortnite', name: 'Fortnite', category: 'Battle Royale / Multijuego', platform: 'PC / Consolas', isMultiPlatformMod: true, keywords: ['fortnite', 'fornite', 'fortnait', 'zero build', 'sin construccion', 'cero construccion', 'reload', 'lego', 'festival', 'racing', 'og'] },
  { id: 'minecraft', name: 'Minecraft', category: 'Supervivencia / Sandbox', platform: 'PC / Consolas', keywords: ['minecraft', 'minecraf', 'maincra', 'mc', 'survival', 'bedwars', 'skywars', 'hardcore', 'mods'] },
  
  // --- MULTIJUGADOR COMPETITIVO & ESPORTS ---
  { id: 'valorant', name: 'Valorant', category: 'Shooter Táctico', platform: 'PC / Consolas', keywords: ['valorant', 'valornat', 'valo', 'vlr'] },
  { id: 'league-of-legends', name: 'League of Legends', category: 'MOBA', platform: 'PC', keywords: ['league of legends', 'lol', 'leag of legends', 'legue of legends', 'tft', 'teamfight tactics', 'aram'] },
  { id: 'counter-strike-2', name: 'Counter-Strike 2', category: 'Shooter Táctico', platform: 'PC', keywords: ['counter strike 2', 'cs2', 'csgo', 'counter', 'cs'] },
  { id: 'dota-2', name: 'Dota 2', category: 'MOBA', platform: 'PC', keywords: ['dota 2', 'dota', 'defense of the ancients'] },
  { id: 'rocket-league', name: 'Rocket League', category: 'Deportes / Acción', platform: 'PC / Consolas', keywords: ['rocket league', 'roquet lig', 'rocket', 'rl'] },
  { id: 'overwatch-2', name: 'Overwatch 2', category: 'Hero Shooter', platform: 'PC / Consolas', keywords: ['overwatch 2', 'overwatch', 'ow2', 'ow'] },
  { id: 'apex-legends', name: 'Apex Legends', category: 'Battle Royale', platform: 'PC / Consolas', keywords: ['apex legends', 'apex', 'apeks'] },
  { id: 'rainbow-six-siege', name: 'Tom Clancy\'s Rainbow Six Siege', category: 'Shooter Táctico', platform: 'PC / Consolas', keywords: ['rainbow six siege', 'r6', 'rainbow six', 'siege'] },
  { id: 'call-of-duty-warzone', name: 'Call of Duty: Warzone', category: 'Battle Royale', platform: 'PC / Consolas', keywords: ['warzone', 'cod warzone', 'call of duty warzone', 'cod'] },
  { id: 'pubg-battlegrounds', name: 'PUBG: BATTLEGROUNDS', category: 'Battle Royale', platform: 'PC / Consolas', keywords: ['pubg', 'playerunknowns battlegrounds', 'pobg'] },
  { id: 'brawlhalla', name: 'Brawlhalla', category: 'Lucha / Plataformas', platform: 'PC / Consolas', keywords: ['brawlhalla', 'brawalla', 'brawl'] },
  { id: 'smite', name: 'Smite', category: 'MOBA', platform: 'PC / Consolas', keywords: ['smite', 'smite 2'] },
  { id: 'dead-by-daylight', name: 'Dead by Daylight', category: 'Terror Asimétrico', platform: 'PC / Consolas', keywords: ['dead by daylight', 'dbd', 'dead by day light'] },

  // --- COOPERATIVOS, FIESTA & PARTY GAMES ---
  { id: 'lethal-company', name: 'Lethal Company', category: 'Terror Cooperativo', platform: 'PC', keywords: ['lethal company', 'lethal', 'letal compani'] },
  { id: 'phasmophobia', name: 'Phasmophobia', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['phasmophobia', 'fasmofobia', 'phasmo', 'fasmo'] },
  { id: 'among-us', name: 'Among Us', category: 'Deducción Social', platform: 'PC / Consolas / Móvil', keywords: ['among us', 'amoung us', 'el impostor', 'sus'] },
  { id: 'fall-guys', name: 'Fall Guys', category: 'Party Royale', platform: 'PC / Consolas', keywords: ['fall guys', 'fal gais', 'fol gais', 'fallguys'] },
  { id: 'content-warning', name: 'Content Warning', category: 'Terror Cooperativo', platform: 'PC', keywords: ['content warning', 'content'] },
  { id: 'chained-together', name: 'Chained Together', category: 'Plataformas Coop', platform: 'PC', keywords: ['chained together', 'encadenados'] },
  { id: 'party-animals', name: 'Party Animals', category: 'Lucha Física / Party', platform: 'PC / Xbox', keywords: ['party animals', 'animales de fiesta'] },
  { id: 'gang-beasts', name: 'Gang Beasts', category: 'Lucha Física / Party', platform: 'PC / Consolas', keywords: ['gang beasts', 'gangbeasts'] },
  { id: 'human-fall-flat', name: 'Human Fall Flat', category: 'Puzzles / Físicas', platform: 'PC / Consolas', keywords: ['human fall flat', 'human fall'] },
  { id: 'overcooked-2', name: 'Overcooked! 2', category: 'Gestión / Cooperativo', platform: 'PC / Consolas', keywords: ['overcooked 2', 'overcooked', 'overcoked'] },
  { id: 'it-takes-two', name: 'It Takes Two', category: 'Aventura Cooperativa', platform: 'PC / Consolas', keywords: ['it takes two', 'it take two'] },
  { id: 'a-way-out', name: 'A Way Out', category: 'Acción Cooperativa', platform: 'PC / Consolas', keywords: ['a way out'] },
  { id: 'pico-park', name: 'PICO PARK', category: 'Puzzles Cooperativos', platform: 'PC / Switch', keywords: ['pico park', 'picopark'] },
  { id: 'goose-goose-duck', name: 'Goose Goose Duck', category: 'Deducción Social', platform: 'PC / Móvil', keywords: ['goose goose duck', 'patos'] },
  { id: 'project-winter', name: 'Project Winter', category: 'Deducción / Supervivencia', platform: 'PC / Consolas', keywords: ['project winter'] },
  { id: 'gmod', name: 'Garry\'s Mod', category: 'Sandbox', platform: 'PC', keywords: ['garrys mod', 'gmod', 'prop hunt', 'ttt', 'trouble in terrorist town'] },
  { id: 'left-4-dead-2', name: 'Left 4 Dead 2', category: 'Shooter Zombis Coop', platform: 'PC', keywords: ['left 4 dead 2', 'l4d2', 'left 4 dead', 'left for dead'] },
  { id: 'deep-rock-galactic', name: 'Deep Rock Galactic', category: 'Shooter Coop', platform: 'PC / Consolas', keywords: ['deep rock galactic', 'drg', 'rock and stone'] },
  { id: 'helldivers-2', name: 'Helldivers 2', category: 'Shooter Cooperativo', platform: 'PC / PS5', keywords: ['helldivers 2', 'helldivers', 'heldivers'] },
  { id: 'sea-of-thieves', name: 'Sea of Thieves', category: 'Aventura Pirata', platform: 'PC / Xbox / PS5', keywords: ['sea of thieves', 'sot', 'piratas'] },
  { id: 'payday-2', name: 'PAYDAY 2', category: 'Atracos Cooperativos', platform: 'PC / Consolas', keywords: ['payday 2', 'payday'] },
  { id: 'payday-3', name: 'PAYDAY 3', category: 'Atracos Cooperativos', platform: 'PC / Consolas', keywords: ['payday 3'] },
  { id: 'unrailed', name: 'Unrailed!', category: 'Construcción Cooperativa', platform: 'PC / Consolas', keywords: ['unrailed'] },
  { id: 'plateup', name: 'PlateUp!', category: 'Gestión / Restaurante Coop', platform: 'PC / Consolas', keywords: ['plateup', 'plate up'] },
  { id: 'speedrunners', name: 'SpeedRunners', category: 'Carreras / Plataformas', platform: 'PC / Consolas', keywords: ['speedrunners', 'speed runners'] },
  { id: 'ultimate-chicken-horse', name: 'Ultimate Chicken Horse', category: 'Plataformas / Fiesta', platform: 'PC / Consolas', keywords: ['ultimate chicken horse', 'chicken horse'] },
  { id: 'duck-game', name: 'Duck Game', category: 'Acción 2D / Fiesta', platform: 'PC / Consolas', keywords: ['duck game'] },
  { id: 'stick-fight', name: 'Stick Fight: The Game', category: 'Lucha 2D / Fiesta', platform: 'PC / Consolas', keywords: ['stick fight', 'stick fight the game'] },
  { id: 'keep-talking-and-nobody-explodes', name: 'Keep Talking and Nobody Explodes', category: 'Puzzles / Comunicación', platform: 'PC / Consolas', keywords: ['keep talking and nobody explodes', 'desactivar bombas'] },
  { id: 'jackbox-party', name: 'The Jackbox Party Pack', category: 'Trivia / Fiesta', platform: 'PC / Consolas', keywords: ['jackbox', 'jackbox party pack', 'trivia murder party', 'quiplash'] },
  { id: 'golf-it', name: 'Golf It!', category: 'Minigolf Multijugador', platform: 'PC', keywords: ['golf it', 'golfit'] },
  { id: 'golf-with-your-friends', name: 'Golf With Your Friends', category: 'Minigolf Multijugador', platform: 'PC / Consolas', keywords: ['golf with your friends'] },
  { id: 'supermarket-together', name: 'Supermarket Together', category: 'Simulación Cooperativa', platform: 'PC', keywords: ['supermarket together', 'supermercado cooperativo'] },
  { id: 'supermarket-simulator', name: 'Supermarket Simulator', category: 'Simulación / Gestión', platform: 'PC', keywords: ['supermarket simulator', 'supermercado simulador'] },
  { id: 'tabletop-simulator', name: 'Tabletop Simulator', category: 'Juegos de Mesa', platform: 'PC', keywords: ['tabletop simulator', 'tabletop'] },
  { id: 'monopoly-plus', name: 'Monopoly Plus', category: 'Juegos de Mesa', platform: 'PC / Consolas', keywords: ['monopoly plus', 'monopoly'] },
  { id: 'uno', name: 'UNO', category: 'Cartas / Fiesta', platform: 'PC / Consolas', keywords: ['uno', 'juego del uno'] },
  { id: 'pinturillo-2', name: 'Pinturillo 2', category: 'Dibujo / Fiesta', platform: 'PC / Web / Móvil', keywords: ['pinturillo 2', 'pinturillo', 'gartic phone', 'gartic'] },
  { id: 'gartic-phone', name: 'Gartic Phone', category: 'Dibujo / Fiesta', platform: 'Web', keywords: ['gartic phone', 'gartic', 'telefono descompuesto'] },
  { id: 'skribbl-io', name: 'Skribbl.io', category: 'Dibujo / Adivinanza', platform: 'Web', keywords: ['skribbl.io', 'skribbl', 'scribble'] },
  { id: 'geoguessr', name: 'GeoGuessr', category: 'Geografía / Trivia', platform: 'Web / PC', keywords: ['geoguessr', 'geoguesser', 'geo guessr'] },

  // --- MUNDO ABIERTO, ACCIÓN & AVENTURA ---
  { id: 'gta-v', name: 'Grand Theft Auto V / GTA Online', category: 'Mundo Abierto / Acción', platform: 'PC / Consolas', keywords: ['gta v', 'gta 5', 'grand theft auto v', 'gta online', 'gta rp', 'fivem'] },
  { id: 'gta-san-andreas', name: 'Grand Theft Auto: San Andreas', category: 'Mundo Abierto / Clásico', platform: 'PC / Consolas', keywords: ['gta san andreas', 'san andreas', 'gta sa', 'cj'] },
  { id: 'gta-vice-city', name: 'Grand Theft Auto: Vice City', category: 'Mundo Abierto / Clásico', platform: 'PC / Consolas', keywords: ['gta vice city', 'vice city'] },
  { id: 'gta-iv', name: 'Grand Theft Auto IV', category: 'Mundo Abierto / Acción', platform: 'PC / Consolas', keywords: ['gta iv', 'gta 4', 'grand theft auto 4', 'niko bellic'] },
  { id: 'red-dead-redemption-2', name: 'Red Dead Redemption 2', category: 'Mundo Abierto / Western', platform: 'PC / Consolas', keywords: ['red dead redemption 2', 'rdr2', 'red dead 2', 'arthur morgan'] },
  { id: 'red-dead-redemption', name: 'Red Dead Redemption', category: 'Mundo Abierto / Western', platform: 'PC / Consolas', keywords: ['red dead redemption', 'rdr1', 'john marston'] },
  { id: 'cyberpunk-2077', name: 'Cyberpunk 2077', category: 'RPG / Acción Cyberpunk', platform: 'PC / Consolas', keywords: ['cyberpunk 2077', 'cyberpunk', 'phantom liberty'] },
  { id: 'the-witcher-3', name: 'The Witcher 3: Wild Hunt', category: 'RPG Fantasía', platform: 'PC / Consolas', keywords: ['the witcher 3', 'witcher 3', 'geralt de rivia'] },
  { id: 'elden-ring', name: 'ELDEN RING', category: 'Soulslike / RPG', platform: 'PC / Consolas', keywords: ['elden ring', 'elden', 'shadow of the erdtree'] },
  { id: 'dark-souls-3', name: 'Dark Souls III', category: 'Soulslike / Acción', platform: 'PC / Consolas', keywords: ['dark souls 3', 'dark souls iii', 'ds3'] },
  { id: 'dark-souls-remastered', name: 'Dark Souls: Remastered', category: 'Soulslike / Acción', platform: 'PC / Consolas', keywords: ['dark souls', 'dark souls remastered', 'ds1'] },
  { id: 'dark-souls-2', name: 'Dark Souls II', category: 'Soulslike / Acción', platform: 'PC / Consolas', keywords: ['dark souls 2', 'dark souls ii', 'ds2'] },
  { id: 'bloodborne', name: 'Bloodborne', category: 'Soulslike / Terror Gótico', platform: 'PS4 / PS5', keywords: ['bloodborne', 'bloodborn'] },
  { id: 'sekiro', name: 'Sekiro: Shadows Die Twice', category: 'Acción / Aventura', platform: 'PC / Consolas', keywords: ['sekiro', 'sekiro shadows die twice'] },
  { id: 'lies-of-p', name: 'Lies of P', category: 'Soulslike', platform: 'PC / Consolas', keywords: ['lies of p', 'pinocho soulslike'] },
  { id: 'black-myth-wukong', name: 'Black Myth: Wukong', category: 'Acción / RPG', platform: 'PC / PS5', keywords: ['black myth wukong', 'wukong', 'mono'] },
  { id: 'god-of-war-ragnarok', name: 'God of War Ragnarök', category: 'Acción / Mitología', platform: 'PC / PS4 / PS5', keywords: ['god of war ragnarok', 'gow ragnarok', 'kratos'] },
  { id: 'god-of-war-2018', name: 'God of War (2018)', category: 'Acción / Aventura', platform: 'PC / PS4 / PS5', keywords: ['god of war', 'gow 2018', 'god of war 4'] },
  { id: 'the-last-of-us-part-1', name: 'The Last of Us Part I', category: 'Supervivencia / Historia', platform: 'PC / PS5', keywords: ['the last of us', 'tlou', 'the last of us parte 1', 'joel y ellie'] },
  { id: 'the-last-of-us-part-2', name: 'The Last of Us Part II', category: 'Supervivencia / Aventura', platform: 'PS4 / PS5', keywords: ['the last of us part 2', 'tlou 2', 'the last of us parte 2'] },
  { id: 'marvel-spider-man-remastered', name: 'Marvel\'s Spider-Man Remastered', category: 'Superhéroes / Acción', platform: 'PC / PS5', keywords: ['spider man', 'spiderman', 'marvel spider man'] },
  { id: 'marvel-spider-man-2', name: 'Marvel\'s Spider-Man 2', category: 'Superhéroes / Acción', platform: 'PS5', keywords: ['spider man 2', 'spiderman 2'] },
  { id: 'marvel-spider-man-miles-morales', name: 'Marvel\'s Spider-Man: Miles Morales', category: 'Superhéroes / Acción', platform: 'PC / Consolas', keywords: ['miles morales', 'spider man miles morales'] },
  { id: 'batman-arkham-knight', name: 'Batman: Arkham Knight', category: 'Superhéroes / Acción', platform: 'PC / Consolas', keywords: ['batman arkham knight', 'arkham knight', 'batman'] },
  { id: 'batman-arkham-city', name: 'Batman: Arkham City', category: 'Superhéroes / Acción', platform: 'PC / Consolas', keywords: ['batman arkham city', 'arkham city'] },
  { id: 'batman-arkham-asylum', name: 'Batman: Arkham Asylum', category: 'Superhéroes / Acción', platform: 'PC / Consolas', keywords: ['batman arkham asylum', 'arkham asylum'] },
  { id: 'hogwarts-legacy', name: 'Hogwarts Legacy', category: 'Mundo Mágico / RPG', platform: 'PC / Consolas', keywords: ['hogwarts legacy', 'harry potter', 'hogwarts'] },
  { id: 'skyrim', name: 'The Elder Scrolls V: Skyrim', category: 'RPG Fantasía', platform: 'PC / Consolas', keywords: ['skyrim', 'the elder scrolls v skyrim', 'dovahkiin', 'tes v'] },
  { id: 'fallout-4', name: 'Fallout 4', category: 'RPG Postapocalíptico', platform: 'PC / Consolas', keywords: ['fallout 4', 'fallout'] },
  { id: 'fallout-new-vegas', name: 'Fallout: New Vegas', category: 'RPG Postapocalíptico', platform: 'PC / Consolas', keywords: ['fallout new vegas', 'new vegas'] },
  { id: 'starfield', name: 'Starfield', category: 'RPG Espacial', platform: 'PC / Xbox', keywords: ['starfield', 'star field'] },
  { id: 'assassins-creed-valhalla', name: 'Assassin\'s Creed Valhalla', category: 'Aventura / Vikingos', platform: 'PC / Consolas', keywords: ['assassins creed valhalla', 'ac valhalla'] },
  { id: 'assassins-creed-odyssey', name: 'Assassin\'s Creed Odyssey', category: 'RPG Grecia Antigua', platform: 'PC / Consolas', keywords: ['assassins creed odyssey', 'ac odyssey'] },
  { id: 'assassins-creed-origins', name: 'Assassin\'s Creed Origins', category: 'RPG Egipto Antiguo', platform: 'PC / Consolas', keywords: ['assassins creed origins', 'ac origins'] },
  { id: 'assassins-creed-mirage', name: 'Assassin\'s Creed Mirage', category: 'Sigilo / Aventura', platform: 'PC / Consolas', keywords: ['assassins creed mirage', 'ac mirage'] },
  { id: 'assassins-creed-black-flag', name: 'Assassin\'s Creed IV: Black Flag', category: 'Aventura Pirata', platform: 'PC / Consolas', keywords: ['assassins creed black flag', 'ac black flag', 'ac 4'] },
  { id: 'assassins-creed-2', name: 'Assassin\'s Creed II', category: 'Aventura / Clásico', platform: 'PC / Consolas', keywords: ['assassins creed 2', 'ezio auditore'] },
  { id: 'far-cry-3', name: 'Far Cry 3', category: 'Shooter / Mundo Abierto', platform: 'PC / Consolas', keywords: ['far cry 3', 'vaas montenegro'] },
  { id: 'far-cry-4', name: 'Far Cry 4', category: 'Shooter / Mundo Abierto', platform: 'PC / Consolas', keywords: ['far cry 4'] },
  { id: 'far-cry-5', name: 'Far Cry 5', category: 'Shooter / Mundo Abierto', platform: 'PC / Consolas', keywords: ['far cry 5'] },
  { id: 'far-cry-6', name: 'Far Cry 6', category: 'Shooter / Mundo Abierto', platform: 'PC / Consolas', keywords: ['far cry 6'] },
  { id: 'watch-dogs', name: 'Watch Dogs', category: 'Hacking / Acción', platform: 'PC / Consolas', keywords: ['watch dogs', 'watchdogs'] },
  { id: 'watch-dogs-2', name: 'Watch Dogs 2', category: 'Hacking / Mundo Abierto', platform: 'PC / Consolas', keywords: ['watch dogs 2'] },
  { id: 'uncharted-4', name: 'Uncharted 4: A Thief\'s End', category: 'Aventura de Tesoros', platform: 'PC / PS4 / PS5', keywords: ['uncharted 4', 'uncharted', 'nathan drake'] },
  { id: 'tomb-raider-2013', name: 'Tomb Raider (2013)', category: 'Supervivencia / Aventura', platform: 'PC / Consolas', keywords: ['tomb raider', 'lara croft'] },
  { id: 'rise-of-the-tomb-raider', name: 'Rise of the Tomb Raider', category: 'Aventura / Puzzles', platform: 'PC / Consolas', keywords: ['rise of the tomb raider'] },
  { id: 'shadow-of-the-tomb-raider', name: 'Shadow of the Tomb Raider', category: 'Aventura / Exploración', platform: 'PC / Consolas', keywords: ['shadow of the tomb raider'] },
  { id: 'ghost-of-tsushima', name: 'Ghost of Tsushima', category: 'Samuráis / Mundo Abierto', platform: 'PC / PS4 / PS5', keywords: ['ghost of tsushima', 'tsushima', 'samurai'] },
  { id: 'horizon-zero-dawn', name: 'Horizon Zero Dawn', category: 'Ciencia Ficción / Mundo Abierto', platform: 'PC / Consolas', keywords: ['horizon zero dawn', 'aloy'] },
  { id: 'horizon-forbidden-west', name: 'Horizon Forbidden West', category: 'Ciencia Ficción / Aventura', platform: 'PC / PS4 / PS5', keywords: ['horizon forbidden west'] },
  { id: 'days-gone', name: 'Days Gone', category: 'Mundo Abierto / Zombis', platform: 'PC / PS4 / PS5', keywords: ['days gone', 'deacon st john'] },
  { id: 'death-stranding', name: 'Death Stranding', category: 'Ciencia Ficción / Aventura', platform: 'PC / Consolas', keywords: ['death stranding', 'hideo kojima', 'sam porter bridges'] },
  { id: 'monster-hunter-world', name: 'Monster Hunter: World', category: 'Caza de Monstruos / RPG', platform: 'PC / Consolas', keywords: ['monster hunter world', 'mhw', 'monster hunter'] },
  { id: 'monster-hunter-rise', name: 'Monster Hunter Rise', category: 'Caza de Monstruos / Acción', platform: 'PC / Consolas / Switch', keywords: ['monster hunter rise', 'mhr'] },
  { id: 'monster-hunter-wilds', name: 'Monster Hunter Wilds', category: 'Caza de Monstruos / RPG', platform: 'PC / Consolas', keywords: ['monster hunter wilds', 'mh wilds'] },
  { id: 'dragons-dogma-2', name: 'Dragon\'s Dogma 2', category: 'RPG Fantasía / Acción', platform: 'PC / Consolas', keywords: ['dragons dogma 2', 'dragons dogma'] },
  { id: 'baldurs-gate-3', name: 'Baldur\'s Gate 3', category: 'RPG Táctico / D&D', platform: 'PC / Consolas', keywords: ['baldurs gate 3', 'bg3', 'baldur gate 3'] },
  { id: 'final-fantasy-vii-remake', name: 'Final Fantasy VII Remake', category: 'JRPG / Acción', platform: 'PC / PS4 / PS5', keywords: ['final fantasy 7 remake', 'ff7 remake', 'cloud strife'] },
  { id: 'final-fantasy-vii-rebirth', name: 'Final Fantasy VII Rebirth', category: 'JRPG / Mundo Abierto', platform: 'PS5', keywords: ['final fantasy 7 rebirth', 'ff7 rebirth'] },
  { id: 'final-fantasy-xvi', name: 'Final Fantasy XVI', category: 'JRPG Acción', platform: 'PC / PS5', keywords: ['final fantasy 16', 'ff16', 'clive'] },
  { id: 'kingdom-hearts-3', name: 'Kingdom Hearts III', category: 'JRPG / Disney', platform: 'PC / Consolas', keywords: ['kingdom hearts 3', 'kh3', 'sora'] },
  { id: 'persona-5-royal', name: 'Persona 5 Royal', category: 'JRPG / Estudiantes', platform: 'PC / Consolas', keywords: ['persona 5 royal', 'p5r', 'persona 5', 'joker'] },
  { id: 'persona-3-reload', name: 'Persona 3 Reload', category: 'JRPG', platform: 'PC / Consolas', keywords: ['persona 3 reload', 'p3r'] },
  { id: 'yakuza-like-a-dragon', name: 'Yakuza: Like a Dragon', category: 'JRPG / Mafias', platform: 'PC / Consolas', keywords: ['yakuza like a dragon', 'ichiban kasuga'] },
  { id: 'like-a-dragon-infinite-wealth', name: 'Like a Dragon: Infinite Wealth', category: 'JRPG / Aventura', platform: 'PC / Consolas', keywords: ['infinite wealth', 'like a dragon infinite wealth', 'yakuza 8'] },
  { id: 'yakuza-0', name: 'Yakuza 0', category: 'Acción / Beat \'em up', platform: 'PC / Consolas', keywords: ['yakuza 0', 'kazuma kiryu', 'goro majima'] },
  { id: 'judgement', name: 'Judgment', category: 'Acción / Detectives', platform: 'PC / Consolas', keywords: ['judgment', 'judgement', 'yagami'] },
  { id: 'lost-judgment', name: 'Lost Judgment', category: 'Acción / Detectives', platform: 'PC / Consolas', keywords: ['lost judgment'] },

  // --- TERROR & SURVIVAL HORROR ---
  { id: 'resident-evil-4-remake', name: 'Resident Evil 4 Remake', category: 'Survival Horror / Acción', platform: 'PC / Consolas', keywords: ['resident evil 4 remake', 're4 remake', 're4', 'leon s kennedy'] },
  { id: 'resident-evil-4-classic', name: 'Resident Evil 4 (2005)', category: 'Survival Horror / Clásico', platform: 'PC / Consolas', keywords: ['resident evil 4 clasico', 're4 2005'] },
  { id: 'resident-evil-2-remake', name: 'Resident Evil 2 Remake', category: 'Survival Horror', platform: 'PC / Consolas', keywords: ['resident evil 2 remake', 're2 remake', 're2', 'mr x'] },
  { id: 'resident-evil-3-remake', name: 'Resident Evil 3 Remake', category: 'Survival Horror / Acción', platform: 'PC / Consolas', keywords: ['resident evil 3 remake', 're3 remake', 'nemesis'] },
  { id: 'resident-evil-7', name: 'Resident Evil 7: Biohazard', category: 'Terror Primera Persona', platform: 'PC / Consolas', keywords: ['resident evil 7', 're7', 'biohazard', 'ethan winters', 'baker'] },
  { id: 'resident-evil-village', name: 'Resident Evil Village', category: 'Terror Gótico / Acción', platform: 'PC / Consolas', keywords: ['resident evil 8', 're8', 'resident evil village', 'lady dimitrescu'] },
  { id: 'silent-hill-2-remake', name: 'Silent Hill 2 Remake', category: 'Terror Psicológico', platform: 'PC / PS5', keywords: ['silent hill 2 remake', 'silent hill 2', 'pyramid head', 'james sunderland'] },
  { id: 'silent-hill-the-short-message', name: 'Silent Hill: The Short Message', category: 'Terror Psicológico', platform: 'PS5', keywords: ['silent hill the short message', 'short message'] },
  { id: 'dead-space-remake', name: 'Dead Space Remake', category: 'Terror Espacial / Sci-Fi', platform: 'PC / Consolas', keywords: ['dead space remake', 'dead space', 'isaac clarke', 'necromorfos'] },
  { id: 'the-callisto-protocol', name: 'The Callisto Protocol', category: 'Terror Espacial', platform: 'PC / Consolas', keywords: ['the callisto protocol', 'callisto protocol'] },
  { id: 'alan-wake-2', name: 'Alan Wake 2', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['alan wake 2', 'alan wake', 'saga anderson'] },
  { id: 'outlast', name: 'Outlast', category: 'Terror / Sigilo', platform: 'PC / Consolas', keywords: ['outlast', 'manicomio', 'miles upshur'] },
  { id: 'outlast-2', name: 'Outlast 2', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['outlast 2', 'blake langermann'] },
  { id: 'the-outlast-trials', name: 'The Outlast Trials', category: 'Terror Cooperativo', platform: 'PC / Consolas', keywords: ['the outlast trials', 'outlast trials'] },
  { id: 'amnesia-the-dark-descent', name: 'Amnesia: The Dark Descent', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['amnesia', 'amnesia the dark descent'] },
  { id: 'amnesia-the-bunker', name: 'Amnesia: The Bunker', category: 'Terror / Supervivencia', platform: 'PC / Consolas', keywords: ['amnesia the bunker', 'amnesia bunker'] },
  { id: 'alien-isolation', name: 'Alien: Isolation', category: 'Terror / Sigilo Sci-Fi', platform: 'PC / Consolas', keywords: ['alien isolation', 'xenomorfo'] },
  { id: 'fears-to-fathom', name: 'Fears to Fathom (Episodios)', category: 'Terror Psicológico / VHS', platform: 'PC', keywords: ['fears to fathom', 'ironbark lookout', 'norwood hitchhike', 'woodbury getaway'] },
  { id: 'fnaf-security-breach', name: 'Five Nights at Freddy\'s: Security Breach', category: 'Terror / Furtivo', platform: 'PC / Consolas', keywords: ['fnaf security breach', 'five nights at freddys security breach', 'fnaf sb', 'gregory', 'glamrock freddy'] },
  { id: 'fnaf-1', name: 'Five Nights at Freddy\'s', category: 'Terror / Clásico', platform: 'PC / Consolas / Móvil', keywords: ['fnaf', 'fnaf 1', 'five nights at freddys', 'freddy fazbear'] },
  { id: 'fnaf-2', name: 'Five Nights at Freddy\'s 2', category: 'Terror', platform: 'PC / Consolas / Móvil', keywords: ['fnaf 2', 'five nights at freddys 2'] },
  { id: 'fnaf-3', name: 'Five Nights at Freddy\'s 3', category: 'Terror', platform: 'PC / Consolas / Móvil', keywords: ['fnaf 3', 'springtrap'] },
  { id: 'fnaf-4', name: 'Five Nights at Freddy\'s 4', category: 'Terror', platform: 'PC / Consolas / Móvil', keywords: ['fnaf 4', 'nightmare freddy'] },
  { id: 'fnaf-sister-location', name: 'Five Nights at Freddy\'s: Sister Location', category: 'Terror', platform: 'PC / Consolas / Móvil', keywords: ['fnaf sister location', 'fnaf sl', 'circus baby'] },
  { id: 'fnaf-help-wanted', name: 'Five Nights at Freddy\'s: Help Wanted', category: 'Terror VR / PC', platform: 'PC / Consolas / VR', keywords: ['fnaf help wanted', 'help wanted'] },
  { id: 'poppy-playtime-chapter-1', name: 'Poppy Playtime (Capítulo 1)', category: 'Terror Mascotas', platform: 'PC / Consolas / Móvil', keywords: ['poppy playtime', 'huggy wuggy', 'poppy playtime capitulo 1'] },
  { id: 'poppy-playtime-chapter-2', name: 'Poppy Playtime (Capítulo 2)', category: 'Terror Mascotas', platform: 'PC / Consolas / Móvil', keywords: ['poppy playtime capitulo 2', 'mommy long legs'] },
  { id: 'poppy-playtime-chapter-3', name: 'Poppy Playtime (Capítulo 3)', category: 'Terror Mascotas', platform: 'PC / Consolas / Móvil', keywords: ['poppy playtime capitulo 3', 'catnap'] },
  { id: 'garten-of-banban', name: 'Garten of Banban', category: 'Terror / Comedia', platform: 'PC / Consolas / Móvil', keywords: ['garten of banban', 'banban'] },
  { id: 'bendy-and-the-ink-machine', name: 'Bendy and the Ink Machine', category: 'Terror Animación', platform: 'PC / Consolas', keywords: ['bendy and the ink machine', 'bendy'] },
  { id: 'bendy-and-the-dark-revival', name: 'Bendy and the Dark Revival', category: 'Terror Aventura', platform: 'PC / Consolas', keywords: ['bendy and the dark revival'] },
  { id: 'the-mortuary-assistant', name: 'The Mortuary Assistant', category: 'Terror Morgue', platform: 'PC / Consolas', keywords: ['the mortuary assistant', 'mortuary assistant', 'autopsias'] },
  { id: 'visage', name: 'Visage', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['visage'] },
  { id: 'madison', name: 'MADiSON', category: 'Terror Psicológico', platform: 'PC / Consolas', keywords: ['madison', 'camara instantanea'] },
  { id: 'soma', name: 'SOMA', category: 'Terror Submarino / Filosófico', platform: 'PC / Consolas', keywords: ['soma'] },
  { id: 'the-evil-within', name: 'The Evil Within', category: 'Survival Horror', platform: 'PC / Consolas', keywords: ['the evil within', 'evil within', 'sebastian castellanos'] },
  { id: 'the-evil-within-2', name: 'The Evil Within 2', category: 'Survival Horror', platform: 'PC / Consolas', keywords: ['the evil within 2', 'evil within 2'] },
  { id: 'little-nightmares', name: 'Little Nightmares', category: 'Terror / Plataformas', platform: 'PC / Consolas', keywords: ['little nightmares', 'six'] },
  { id: 'little-nightmares-2', name: 'Little Nightmares II', category: 'Terror / Puzzles', platform: 'PC / Consolas', keywords: ['little nightmares 2', 'mono y six'] },
  { id: 'inside', name: 'INSIDE', category: 'Puzzles / Distopía', platform: 'PC / Consolas', keywords: ['inside'] },
  { id: 'limbo', name: 'LIMBO', category: 'Plataformas / Oscuridad', platform: 'PC / Consolas', keywords: ['limbo'] },

  // --- SUPERVIVENCIA, CRAFTING & SIMULACIÓN ---
  { id: 'palworld', name: 'Palworld', category: 'Supervivencia / Criaturas', platform: 'PC / Xbox / PS5', keywords: ['palworld', 'pokemon con pistolas', 'pals'] },
  { id: 'rust', name: 'Rust', category: 'Supervivencia PvP', platform: 'PC / Consolas', keywords: ['rust'] },
  { id: 'ark-survival-ascended', name: 'ARK: Survival Ascended', category: 'Supervivencia Dinosaurios', platform: 'PC / Consolas', keywords: ['ark survival ascended', 'ark ascended', 'ark dinosaurios'] },
  { id: 'ark-survival-evolved', name: 'ARK: Survival Evolved', category: 'Supervivencia Dinosaurios', platform: 'PC / Consolas', keywords: ['ark survival evolved', 'ark'] },
  { id: 'sons-of-the-forest', name: 'Sons of the Forest', category: 'Supervivencia Caníbales', platform: 'PC', keywords: ['sons of the forest', 'kelvin', 'canibales'] },
  { id: 'the-forest', name: 'The Forest', category: 'Supervivencia / Terror', platform: 'PC / Consolas', keywords: ['the forest'] },
  { id: 'subnautica', name: 'Subnautica', category: 'Supervivencia Submarina', platform: 'PC / Consolas', keywords: ['subnautica', 'leviatan'] },
  { id: 'subnautica-below-zero', name: 'Subnautica: Below Zero', category: 'Supervivencia Polar', platform: 'PC / Consolas', keywords: ['subnautica below zero'] },
  { id: 'terraria', name: 'Terraria', category: 'Aventura 2D / Sandbox', platform: 'PC / Consolas / Móvil', keywords: ['terraria', 'terraria 2d'] },
  { id: 'valheim', name: 'Valheim', category: 'Supervivencia Vikinga', platform: 'PC / Xbox', keywords: ['valheim'] },
  { id: 'dont-starve-together', name: 'Don\'t Starve Together', category: 'Supervivencia Gótica', platform: 'PC / Consolas', keywords: ['dont starve together', 'dont starve', 'dst'] },
  { id: 'project-zomboid', name: 'Project Zomboid', category: 'Supervivencia Zombi Isométrica', platform: 'PC', keywords: ['project zomboid', 'zomboid'] },
  { id: '7-days-to-die', name: '7 Days to Die', category: 'Supervivencia / Hordas Zombi', platform: 'PC / Consolas', keywords: ['7 days to die', '7dtd'] },
  { id: 'dayz', name: 'DayZ', category: 'Supervivencia Zombi Hardcore', platform: 'PC / Consolas', keywords: ['dayz', 'day z'] },
  { id: 'escape-from-tarkov', name: 'Escape from Tarkov', category: 'Extraction Shooter', platform: 'PC', keywords: ['escape from tarkov', 'tarkov', 'eft'] },
  { id: 'stardew-valley', name: 'Stardew Valley', category: 'Simulación de Granja / RPG', platform: 'PC / Consolas / Móvil', keywords: ['stardew valley', 'stardew', 'granja'] },
  { id: 'animal-crossing-new-horizons', name: 'Animal Crossing: New Horizons', category: 'Simulación de Vida', platform: 'Switch', keywords: ['animal crossing new horizons', 'animal crossing', 'acnh'] },
  { id: 'the-sims-4', name: 'Los Sims 4', category: 'Simulación de Vida', platform: 'PC / Consolas', keywords: ['los sims 4', 'sims 4', 'the sims 4', 'sims'] },
  { id: 'euro-truck-simulator-2', name: 'Euro Truck Simulator 2', category: 'Simulación de Camiones', platform: 'PC', keywords: ['euro truck simulator 2', 'ets2', 'euro truck'] },
  { id: 'american-truck-simulator', name: 'American Truck Simulator', category: 'Simulación de Camiones', platform: 'PC', keywords: ['american truck simulator', 'ats'] },
  { id: 'flight-simulator-2024', name: 'Microsoft Flight Simulator 2024', category: 'Simulación de Aviación', platform: 'PC / Xbox', keywords: ['microsoft flight simulator 2024', 'flight simulator', 'mfs'] },
  { id: 'powerwash-simulator', name: 'PowerWash Simulator', category: 'Simulación Relajante', platform: 'PC / Consolas', keywords: ['powerwash simulator', 'lavar a presion'] },
  { id: 'house-flipper-2', name: 'House Flipper 2', category: 'Reformas / Renovación', platform: 'PC / Consolas', keywords: ['house flipper 2', 'house flipper'] },
  { id: 'gas-station-simulator', name: 'Gas Station Simulator', category: 'Gestión de Gasolinera', platform: 'PC / Consolas', keywords: ['gas station simulator'] },
  { id: 'tcg-card-shop-simulator', name: 'TCG Card Shop Simulator', category: 'Simulación / Cartas', platform: 'PC', keywords: ['tcg card shop simulator', 'tienda de cartas', 'tcg simulator'] },
  { id: 'supermarket-cashier-simulator', name: 'Supermarket Cashier Simulator', category: 'Simulación de Cajero', platform: 'PC', keywords: ['supermarket cashier simulator'] },
  { id: 'internet-cafe-simulator-2', name: 'Internet Cafe Simulator 2', category: 'Simulación de Cibercafé', platform: 'PC', keywords: ['internet cafe simulator 2', 'cibercafe'] },
  { id: 'thief-simulator-2', name: 'Thief Simulator 2', category: 'Simulación de Ladrones', platform: 'PC / Consolas', keywords: ['thief simulator 2', 'thief simulator'] },
  { id: 'car-mechanic-simulator-2021', name: 'Car Mechanic Simulator 2021', category: 'Simulación Mecánica', platform: 'PC / Consolas', keywords: ['car mechanic simulator 2021', 'mecanico'] },
  { id: 'satisfactory', name: 'Satisfactory', category: 'Automatización / Fábricas', platform: 'PC', keywords: ['satisfactory', 'fabricas'] },
  { id: 'factorio', name: 'Factorio', category: 'Automatización Industrial', platform: 'PC / Switch', keywords: ['factorio'] },
  { id: 'rimworld', name: 'RimWorld', category: 'Colonia / Supervivencia', platform: 'PC / Consolas', keywords: ['rimworld', 'rim world'] },
  { id: 'cities-skylines-2', name: 'Cities: Skylines II', category: 'Construcción de Ciudades', platform: 'PC / Consolas', keywords: ['cities skylines 2', 'cities skylines'] },

  // --- NINTENDO, PLATAFORMAS & CLÁSICOS ---
  { id: 'super-mario-odyssey', name: 'Super Mario Odyssey', category: 'Plataformas 3D', platform: 'Switch', keywords: ['super mario odyssey', 'mario odyssey', 'cappy'] },
  { id: 'super-mario-bros-wonder', name: 'Super Mario Bros. Wonder', category: 'Plataformas 2D', platform: 'Switch', keywords: ['super mario bros wonder', 'mario wonder'] },
  { id: 'super-mario-64', name: 'Super Mario 64', category: 'Plataformas / Retro', platform: 'N64 / PC / Switch', keywords: ['super mario 64', 'mario 64'] },
  { id: 'mario-kart-8-deluxe', name: 'Mario Kart 8 Deluxe', category: 'Carreras Karts / Fiesta', platform: 'Switch', keywords: ['mario kart 8 deluxe', 'mario kart 8', 'mario kart', 'mk8'] },
  { id: 'super-smash-bros-ultimate', name: 'Super Smash Bros. Ultimate', category: 'Lucha Plataformas', platform: 'Switch', keywords: ['super smash bros ultimate', 'smash ultimate', 'smash bros', 'ssbu'] },
  { id: 'super-mario-party-jamboree', name: 'Super Mario Party Jamboree', category: 'Fiesta / Minijuegos', platform: 'Switch', keywords: ['super mario party jamboree', 'mario party jamboree', 'mario party'] },
  { id: 'the-legend-of-zelda-tears-of-the-kingdom', name: 'The Legend of Zelda: Tears of the Kingdom', category: 'Aventura / Mundo Abierto', platform: 'Switch', keywords: ['tears of the kingdom', 'totk', 'zelda totk', 'zelda tears of the kingdom'] },
  { id: 'the-legend-of-zelda-breath-of-the-wild', name: 'The Legend of Zelda: Breath of the Wild', category: 'Aventura / Mundo Abierto', platform: 'Switch / Wii U', keywords: ['breath of the wild', 'botw', 'zelda botw', 'zelda breath of the wild'] },
  { id: 'the-legend-of-zelda-ocarina-of-time', name: 'The Legend of Zelda: Ocarina of Time', category: 'Aventura / Retro Clásico', platform: 'N64 / 3DS', keywords: ['ocarina of time', 'oot', 'zelda ocarina of time'] },
  { id: 'the-legend-of-zelda-majoras-mask', name: 'The Legend of Zelda: Majora\'s Mask', category: 'Aventura / Oscuro', platform: 'N64 / 3DS', keywords: ['majoras mask', 'zelda majoras mask'] },
  { id: 'pokemon-scarlet-violet', name: 'Pokémon Escarlata y Púrpura', category: 'RPG / Criaturas', platform: 'Switch', keywords: ['pokemon escarlata y purpura', 'pokemon scarlet violet', 'pokemon escarlata', 'pokemon purpura'] },
  { id: 'pokemon-legends-arceus', name: 'Leyendas Pokémon: Arceus', category: 'RPG / Acción', platform: 'Switch', keywords: ['leyendas pokemon arceus', 'pokemon legends arceus', 'arceus'] },
  { id: 'pokemon-esmeralda', name: 'Pokémon Esmeralda', category: 'JRPG / Retro Clásico', platform: 'GBA / Emulador', keywords: ['pokemon esmeralda', 'pokemon emerald', 'rayquaza'] },
  { id: 'pokemon-platino', name: 'Pokémon Platino', category: 'JRPG / Retro', platform: 'NDS / Emulador', keywords: ['pokemon platino', 'pokemon platinum', 'giratina'] },
  { id: 'pokemon-blanco-negro', name: 'Pokémon Blanco y Negro', category: 'JRPG / Retro', platform: 'NDS / Emulador', keywords: ['pokemon blanco', 'pokemon negro', 'pokemon black', 'pokemon white'] },
  { id: 'pokemon-corazon-oro-alma-plata', name: 'Pokémon HeartGold y SoulSilver', category: 'JRPG / Clásico', platform: 'NDS / Emulador', keywords: ['pokemon heartgold', 'pokemon soulsilver', 'pokemon oro', 'pokemon plata'] },
  { id: 'metroid-dread', name: 'Metroid Dread', category: 'Metroidvania / Acción', platform: 'Switch', keywords: ['metroid dread', 'samus aran', 'emmi'] },
  { id: 'metroid-prime-remastered', name: 'Metroid Prime Remastered', category: 'Aventura Primera Persona', platform: 'Switch', keywords: ['metroid prime remastered', 'metroid prime'] },
  { id: 'luigis-mansion-3', name: 'Luigi\'s Mansion 3', category: 'Aventura / Fantasmas', platform: 'Switch', keywords: ['luigis mansion 3', 'luigi mansion 3', 'luigi'] },
  { id: 'donkey-kong-country-tropical-freeze', name: 'Donkey Kong Country: Tropical Freeze', category: 'Plataformas 2D', platform: 'Switch / Wii U', keywords: ['donkey kong tropical freeze', 'donkey kong'] },
  { id: 'sonic-frontiers', name: 'Sonic Frontiers', category: 'Plataformas / Mundo Abierto', platform: 'PC / Consolas', keywords: ['sonic frontiers', 'sonic'] },
  { id: 'sonic-x-shadow-generations', name: 'SONIC X SHADOW GENERATIONS', category: 'Plataformas Acción', platform: 'PC / Consolas', keywords: ['sonic x shadow generations', 'shadow generations', 'sonic shadow'] },
  { id: 'crash-bandicoot-4', name: 'Crash Bandicoot 4: It\'s About Time', category: 'Plataformas 3D', platform: 'PC / Consolas', keywords: ['crash bandicoot 4', 'crash 4', 'crash bandicoot'] },
  { id: 'crash-bandicoot-n-sane-trilogy', name: 'Crash Bandicoot N. Sane Trilogy', category: 'Plataformas Clásico', platform: 'PC / Consolas', keywords: ['crash bandicoot n sane trilogy', 'crash trilogy'] },
  { id: 'spyro-reignited-trilogy', name: 'Spyro Reignited Trilogy', category: 'Plataformas / Aventura', platform: 'PC / Consolas', keywords: ['spyro reignited trilogy', 'spyro'] },
  { id: 'cuphead', name: 'Cuphead', category: 'Run & Gun / Jefes', platform: 'PC / Consolas', keywords: ['cuphead', 'mugman', 'dlc delicious last course'] },
  { id: 'hollow-knight', name: 'Hollow Knight', category: 'Metroidvania', platform: 'PC / Consolas', keywords: ['hollow knight', 'hollowknight', 'caballero', 'silksong'] },
  { id: 'hollow-knight-silksong', name: 'Hollow Knight: Silksong', category: 'Metroidvania', platform: 'PC / Consolas', keywords: ['hollow knight silksong', 'silksong', 'hornet'] },
  { id: 'celeste', name: 'Celeste', category: 'Plataformas Precisión', platform: 'PC / Consolas', keywords: ['celeste', 'madeline'] },
  { id: 'dead-cells', name: 'Dead Cells', category: 'Roguelite / Acción', platform: 'PC / Consolas', keywords: ['dead cells'] },
  { id: 'hades', name: 'Hades', category: 'Roguelike de Acción', platform: 'PC / Consolas', keywords: ['hades', 'zagreus'] },
  { id: 'hades-2', name: 'Hades II', category: 'Roguelike de Acción', platform: 'PC', keywords: ['hades 2', 'hades ii', 'melinoe'] },
  { id: 'the-binding-of-isaac-repentance', name: 'The Binding of Isaac: Repentance', category: 'Roguelike / Mazmorras', platform: 'PC / Consolas', keywords: ['the binding of isaac', 'isaac repentance', 'binding of isaac'] },
  { id: 'slay-the-spire', name: 'Slay the Spire', category: 'Deckbuilder Roguelike', platform: 'PC / Consolas / Móvil', keywords: ['slay the spire', 'cartas roguelike'] },
  { id: 'balatro', name: 'Balatro', category: 'Póker Roguelike', platform: 'PC / Consolas / Móvil', keywords: ['balatro', 'poker roguelike', 'jokers'] },
  { id: 'vampire-survivors', name: 'Vampire Survivors', category: 'Auto-Shooter / Roguelite', platform: 'PC / Consolas / Móvil', keywords: ['vampire survivors'] },
  { id: 'enter-the-gungeon', name: 'Enter the Gungeon', category: 'Bullet Hell / Mazmorras', platform: 'PC / Consolas', keywords: ['enter the gungeon'] },
  { id: 'cult-of-the-lamb', name: 'Cult of the Lamb', category: 'Roguelike / Gestión', platform: 'PC / Consolas', keywords: ['cult of the lamb', 'el cordero'] },
  { id: 'undertale', name: 'Undertale', category: 'RPG Indie / Narrativa', platform: 'PC / Consolas', keywords: ['undertale', 'sans', 'papyrus', 'frisk', 'megalovania'] },
  { id: 'deltarune', name: 'DELTARUNE', category: 'RPG Indie', platform: 'PC / Consolas', keywords: ['deltarune', 'kris', 'susie', 'ralsei', 'spamton'] },
  { id: 'omori', name: 'OMORI', category: 'RPG Psicológico', platform: 'PC / Consolas', keywords: ['omori', 'sunny', 'basil'] },
  { id: 'hotline-miami', name: 'Hotline Miami', category: 'Acción Top-Down', platform: 'PC / Consolas', keywords: ['hotline miami', 'jacket'] },
  { id: 'geometry-dash', name: 'Geometry Dash', category: 'Ritmo / Plataformas', platform: 'PC / Móvil', keywords: ['geometry dash', 'gd', 'robtop'] },
  { id: 'osu', name: 'osu!', category: 'Juego de Ritmo', platform: 'PC', keywords: ['osu', 'osu!mania', 'osu taiko'] },
  { id: 'beat-saber', name: 'Beat Saber', category: 'Ritmo / VR', platform: 'VR', keywords: ['beat saber', 'sables de luz'] },

  // --- LUCHA & DEPORTES ---
  { id: 'street-fighter-6', name: 'Street Fighter 6', category: 'Lucha 2D', platform: 'PC / Consolas', keywords: ['street fighter 6', 'sf6', 'ryu', 'ken'] },
  { id: 'tekken-8', name: 'TEKKEN 8', category: 'Lucha 3D', platform: 'PC / Consolas', keywords: ['tekken 8', 'tekken', 'jin kazama', 'kazuya'] },
  { id: 'mortal-kombat-1', name: 'Mortal Kombat 1', category: 'Lucha Sangrienta', platform: 'PC / Consolas', keywords: ['mortal kombat 1', 'mk1', 'mortal kombat', 'scorpion', 'sub zero'] },
  { id: 'mortal-kombat-11', name: 'Mortal Kombat 11', category: 'Lucha Sangrienta', platform: 'PC / Consolas', keywords: ['mortal kombat 11', 'mk11'] },
  { id: 'dragon-ball-sparking-zero', name: 'DRAGON BALL: Sparking! ZERO', category: 'Lucha Arena 3D / Anime', platform: 'PC / PS5 / Xbox Series', keywords: ['dragon ball sparking zero', 'sparking zero', 'budokai tenkaichi 4', 'goku', 'vegeta'] },
  { id: 'dragon-ball-fighterz', name: 'Dragon Ball FighterZ', category: 'Lucha 2.5D Anime', platform: 'PC / Consolas', keywords: ['dragon ball fighterz', 'dbfz'] },
  { id: 'dragon-ball-xenoverse-2', name: 'Dragon Ball Xenoverse 2', category: 'Lucha RPG / Anime', platform: 'PC / Consolas', keywords: ['dragon ball xenoverse 2', 'xenoverse 2'] },
  { id: 'naruto-shippuden-ultimate-ninja-storm-4', name: 'Naruto Shippuden: Ultimate Ninja Storm 4', category: 'Lucha Anime', platform: 'PC / Consolas', keywords: ['naruto storm 4', 'ninja storm 4', 'naruto'] },
  { id: 'ea-sports-fc-25', name: 'EA SPORTS FC 25', category: 'Fútbol / Deportes', platform: 'PC / Consolas', keywords: ['ea fc 25', 'fc 25', 'fifa 25', 'fifa', 'ultimate team'] },
  { id: 'ea-sports-fc-24', name: 'EA SPORTS FC 24', category: 'Fútbol / Deportes', platform: 'PC / Consolas', keywords: ['ea fc 24', 'fc 24', 'fifa 24'] },
  { id: 'efootball', name: 'eFootball 2025', category: 'Fútbol / Deportes', platform: 'PC / Consolas / Móvil', keywords: ['efootball', 'pes', 'pro evolution soccer'] },
  { id: 'nba-2k25', name: 'NBA 2K25', category: 'Baloncesto / Deportes', platform: 'PC / Consolas', keywords: ['nba 2k25', 'nba 2k', 'nba'] },
  { id: 'wwe-2k24', name: 'WWE 2K24', category: 'Lucha Libre / Deportes', platform: 'PC / Consolas', keywords: ['wwe 2k24', 'wwe', 'wrestling'] },
  { id: 'forza-horizon-5', name: 'Forza Horizon 5', category: 'Carreras / Mundo Abierto', platform: 'PC / Xbox', keywords: ['forza horizon 5', 'forza 5', 'forza horizon'] },
  { id: 'forza-motorsport', name: 'Forza Motorsport', category: 'Simulador de Carreras', platform: 'PC / Xbox', keywords: ['forza motorsport'] },
  { id: 'assetto-corsa', name: 'Assetto Corsa', category: 'Simulador de Carreras', platform: 'PC / Consolas', keywords: ['assetto corsa', 'simracing', 'no hesi'] },
  { id: 'f1-24', name: 'F1 24', category: 'Fórmula 1 / Carreras', platform: 'PC / Consolas', keywords: ['f1 24', 'formula 1', 'f1'] },
  { id: 'need-for-speed-unbound', name: 'Need for Speed Unbound', category: 'Carreras Callejeras', platform: 'PC / Consolas', keywords: ['need for speed unbound', 'nfs unbound', 'need for speed'] },
  { id: 'need-for-speed-heat', name: 'Need for Speed Heat', category: 'Carreras Callejeras', platform: 'PC / Consolas', keywords: ['need for speed heat', 'nfs heat'] },
  { id: 'need-for-speed-most-wanted', name: 'Need for Speed: Most Wanted (2005)', category: 'Carreras / Clásico', platform: 'PC / Consolas', keywords: ['nfs most wanted', 'most wanted 2005', 'bmw m3 gtr'] },
  { id: 'burnout-paradise-remastered', name: 'Burnout Paradise Remastered', category: 'Carreras / Destrucción', platform: 'PC / Consolas', keywords: ['burnout paradise', 'burnout'] },
  { id: 'the-crew-motorfest', name: 'The Crew Motorfest', category: 'Carreras Festival', platform: 'PC / Consolas', keywords: ['the crew motorfest', 'motorfest'] }
];
